#
# Workflow to build all relevant firmware configurations to make sure nothing has broken
#
name: CI

# Controls when the workflow will run
on:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on:
      - ubuntu-latest

    defaults:
      run:
        shell: bash -l {0}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Install latest cmake
      - uses: lukka/get-cmake@latest

      - name: Checkout submodules
        run: |
          git submodule update --init third_party/googletest

      - name: Run tests
        run: |
          mkdir build
          cd build
          cmake ../
          make -j
          ctest --output-on-failure
